import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "@/components/SiteHeader";
import { getStarkvilleGuide, starkvilleGuides } from "@/lib/starkville-guides";
import { safeJsonLd, siteUrl } from "@/lib/seo";

export function generateStaticParams(){return starkvilleGuides.map(guide=>({slug:guide.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const guide=getStarkvilleGuide((await params).slug);return guide?{title:guide.title,description:guide.description,alternates:{canonical:`/starkville/${guide.slug}`},openGraph:{title:guide.title,description:guide.description,type:"article",images:["/rosey-originals/deck.jpg"]}}:{};}
export default async function GuidePage({params}:{params:Promise<{slug:string}>}){const guide=getStarkvilleGuide((await params).slug);if(!guide)notFound();const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"Article",headline:guide.title,description:guide.description,datePublished:"2026-07-31",dateModified:"2026-07-31",author:{"@type":"Organization",name:"Rosey Baby"},publisher:{"@id":`${siteUrl}/#restaurant`},mainEntityOfPage:`${siteUrl}/starkville/${guide.slug}`},{"@type":"FAQPage",mainEntity:guide.faqs.map(faq=>({"@type":"Question",name:faq.question,acceptedAnswer:{"@type":"Answer",text:faq.answer}}))},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:siteUrl},{"@type":"ListItem",position:2,name:"Starkville guide",item:`${siteUrl}/starkville`},{"@type":"ListItem",position:3,name:guide.title,item:`${siteUrl}/starkville/${guide.slug}`}]}]};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(jsonLd)}}/><SiteHeader/><article className="guide-page"><header><p className="eyebrow">Rosey Baby’s local guide · Updated July 31, 2026</p><h1>{guide.title}</h1><p>{guide.description}</p></header><div className="guide-direct-answer"><h2>Quick answer</h2><p>{guide.answer}</p></div><div className="guide-body">{guide.sections.map(section=><section key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p></section>)}<section><h2>Official sources</h2><ul>{guide.sources.map(source=><li key={source.url}><a href={source.url}>{source.label} ↗</a></li>)}</ul></section><section><h2>Frequently asked questions</h2>{guide.faqs.map(faq=><div className="guide-faq" key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></div>)}</section></div><aside><div><h2>Make Rosey Baby one stop.</h2><p>300 South Jackson Street · Monday–Saturday, 11 AM–10 PM.</p></div><Link className="button button-primary" href="/visit">Plan your visit →</Link></aside></article></main>}
