import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "@/components/SiteHeader";
import { getEvent, getEvents } from "@/lib/editorial";
import { siteUrl } from "@/lib/seo";
import JsonLd from "@/components/JsonLd";

export const revalidate=3600;
export async function generateStaticParams(){return (await getEvents()).slice(0,50).map(event=>({slug:event.slug!}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const event=await getEvent(slug);return event?{title:event.title,description:event.description,alternates:{canonical:`/events/${slug}`},openGraph:{title:event.title,description:event.description,type:"article",images:[event.imageUrl||"/rosey-originals/deck.jpg"]}}:{};}

export default async function EventPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const event=await getEvent(slug);if(!event)notFound();const date=event.startsAt?new Intl.DateTimeFormat("en-US",{dateStyle:"full",timeStyle:"short",timeZone:"America/Chicago"}).format(new Date(event.startsAt)):event.dateLabel||"Date pending";const jsonLd={"@context":"https://schema.org","@type":"Event",name:event.title,startDate:event.startsAt,endDate:event.endsAt,description:event.description,image:[event.imageUrl||`${siteUrl}/rosey-originals/deck.jpg`],eventAttendanceMode:"https://schema.org/OfflineEventAttendanceMode",eventStatus:"https://schema.org/EventScheduled",location:{"@type":"Place",name:event.location,address:{"@type":"PostalAddress",streetAddress:event.streetAddress,addressLocality:event.city||"Starkville",addressRegion:event.region||"MS",postalCode:event.postalCode}},organizer:{"@type":"Organization",name:event.organizer||"Event organizer",url:event.organizerUrl||event.sourceUrl},...(event.ticketUrl?{offers:{"@type":"Offer",url:event.ticketUrl,availability:"https://schema.org/InStock"}}:{}),url:`${siteUrl}/events/${slug}`};return <main id="main-content"><JsonLd data={jsonLd}/><SiteHeader/><article className="article-page"><header><p className="eyebrow">{event.eventType} · {date}</p><h1>{event.title}</h1><p>{event.description}</p></header><div className="article-body"><h2>Plan around the event</h2><p><strong>Where:</strong> {event.location}</p><p><strong>When:</strong> {date}</p><p>Rosey Baby is at 300 South Jackson Street near downtown Starkville. Large groups should reserve ahead on MSU game days and major downtown weekends.</p><p><a href={event.sourceUrl}>Check the official event source for the latest time, admission, parking, and weather updates ↗</a></p></div><aside><div><h2>Meet before or after.</h2><p>Cajun food, cold beer, and room for the whole crew.</p></div><Link className="button button-primary" href="https://www.opentable.com/r/rosey-baby-starkville">Reserve a table →</Link></aside></article></main>}
